### ISSUE TITLE
[Feature Request] Cross-platform

### ISSUE THREAD

**Issue by TravorLZH** [ZYFDroid/HackerBomberScript#4]
（我从B站过来的）的确，可见UP还是花了不少精力在这个上面，但是UP是否考虑过移植问题。为何不把这个神奇的工具封装成一个库，以便更多人接入。

**Comment by Dobby233Liu** [comment]
> [Feature Request] Charset encoding problem
> **\=\=**
> [新功能请求] 字符集编码问题

所以你在提交什么问题/新功能？
ScriptInterpreter 已经在 https://github.com/ZYFDroid/HackerBomberScript/commit/ba6c9cad9da909a4b07877a9e250151ad8fffc09 这个 commit 里[封装成库](https://github.com/ZYFDroid/HackerBomberScript/commit/ba6c9cad9da909a4b07877a9e250151ad8fffc09#diff-b18bc98368e9b44f6d4861ec8e19d523)了。(edit: windows库)

**Comment by ZYFDroid** [comment]
计划通过Xamarin移植到安卓平台

**Comment by TravorLZH** [comment]
就是要求源代码文件声明具体编码，如gb**，UTF-8等

**Comment by Dobby233Liu** [comment]
> 就是要求源代码文件声明具体编码，如gb**，UTF-8等

源代码编码？我看了一下，好像全是UTF-8 with BOM

**Comment by TravorLZH** [comment]
有些地方还是在使用GBK，ISO**，我建议可以如同Python一样通过注释声明，以免在读取文件时出现意外，另一种方案就是直接简化比如第一行填写服务器域名、第二行端口、第三行协议、第四行query string的格式输出。因为真正用户在使用时是不关心关键字的。这样也省去了你的程序的排错过程

**Comment by TravorLZH** [comment]
> ScriptInterpreter 已经在 [ba6c9ca](https://github.com/ZYFDroid/HackerBomberScript/commit/ba6c9cad9da909a4b07877a9e250151ad8fffc09) 这个 commit 里[封装成库](https://github.com/ZYFDroid/HackerBomberScript/commit/ba6c9cad9da909a4b07877a9e250151ad8fffc09#diff-b18bc98368e9b44f6d4861ec8e19d523)了。(edit: windows库)

我之所以请求封装成库是因为可以让其它跨平台应用更好接入

**Comment by TravorLZH** [comment]
还有改用CMake也可以省去用户花大量精力去装Visual Studio（毕竟不是所有的平台都青睐.net）

EDIT：当我没说，msbuild也还好。不过我在考虑是否应该该用一个更偏基础（如C/C++）都编程语言进行封装。毕竟C#还要和各种个样都对象打交道，并且主要支持还是Windows

**Comment by ZYFDroid** [comment]
文件编码问题目前还没遇到过，不过预计统一为UTF-8，至于跨平台，你可以把代码搬到Unity3D上，安卓，IOS，Xbox主机，HoloLens，或者弄到Xamarin上，轻量级

**Comment by ZYFDroid** [comment]
跨平台已实现
